name: Build wine 

on:
  push:
    tags:
      - 'wine-*-v*'
      - 'wine-[a-zA-Z]+-v[0-9]+.[0-9]+'
    branches:
      - 'wine-*-v*'
      - 'wine-[a-zA-Z]+-v[0-9]+.[0-9]+'

jobs:
  x86:
    uses: ./.github/workflows/build_wine_arch.yml
    with:
      wine_arch: "x86"

  arm64ec:
    uses: ./.github/workflows/build_wine_arch.yml
    with:
      wine_arch: "arm64ec"
